apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fpe-nginx-ingress
spec:
  rules:
  - host: nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-fpe-nginx
            port:
              number: 80